#!/command/with-contenv sh

QUEUE_PID=$(pgrep -f "/usr/local/bin/php /var/www/artisan queue:work --queue=emails,images,thumbnails")
if [ -z "$QUEUE_PID" ]; then
    echo "❎ QUEUE STOP."
    exit 1
else
    echo "✅ QUEUE RUN."
    exit 0
fi
